version: "3.8"

services:
  app:
    build: .
    ports:
      - "5000:5000"

    env_file:
      - .env

    depends_on:
      - redis
    volumes:
      - .:/app

    command: npm start

    restart: always

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
